source <sfile>:h/vimrc.d/enable-plugins.vim
source <sfile>:h/vimrc.d/disable-plugins.vim
source <sfile>:h/vimrc.d/configure-plugins.vim
source <sfile>:h/vimrc.d/defaults.vim
source <sfile>:h/vimrc.d/autocommands.vim
source <sfile>:h/vimrc.d/commands.vim
source <sfile>:h/vimrc.d/mappings/normal-visual.vim
source <sfile>:h/vimrc.d/mappings/terminal.vim
source <sfile>:h/vimrc.d/work.vim
